// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package watchdebugger

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/laenen-partners/dsx/ds"
	"github.com/laenen-partners/dsx/utils"
)

// DebugSignals holds the debugger's reactive state.
type DebugSignals struct {
	Open      bool  `json:"open"`
	Connected bool  `json:"connected"`
	LastTs    int64 `json:"lastTs"`
}

// Props configures the watch debugger panel.
type Props struct {
	// ID uniquely identifies this debugger instance.
	ID string
	// Class adds CSS classes to the outer wrapper.
	Class string
	// Attributes adds arbitrary HTML attributes.
	Attributes templ.Attributes
	// MaxEvents is the maximum number of log entries to keep. Default: 50.
	MaxEvents int
}

func (p *Props) defaults() {
	if p.ID == "" {
		p.ID = "watch-dbg"
	}
	if p.MaxEvents <= 0 {
		p.MaxEvents = 50
	}
}

// WatchDebugger renders a floating inspector panel that shows active watches,
// SSE connection state, live signal values, and a scrolling event log.
//
// Usage:
//
//	@watchdebugger.WatchDebugger()
//	@watchdebugger.WatchDebugger(watchdebugger.Props{MaxEvents: 100})
func WatchDebugger(props ...Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var p Props
		if len(props) > 0 {
			p = props[0]
		}
		p.defaults()
		signals := ds.NewSignals(p.ID, DebugSignals{})
		maxEvt := p.MaxEvents

		// Expression for the signal-patch handler: accumulates events into a
		// window-side array and renders them into the log element.
		logExpr := fmt.Sprintf(
			"window.__dsDbgLog=window.__dsDbgLog||[];"+
				"var _p=JSON.stringify(patch);"+
				"var _now=new Date().toLocaleTimeString();"+
				"window.__dsDbgLog.unshift(_now+' '+_p);"+
				"if(window.__dsDbgLog.length>%d)window.__dsDbgLog.length=%d;"+
				"var _el=document.getElementById('%s-log');"+
				"if(_el)_el.textContent=window.__dsDbgLog.join('\\n');"+
				"%s=true;%s=Date.now()",
			maxEvt, maxEvt, p.ID,
			signals.Signal("connected"), signals.Signal("lastTs"),
		)
		var templ_7745c5c3_Var2 = []any{utils.TwMerge("fixed bottom-4 right-4 z-50", p.Class)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/watchdebugger/watchdebugger.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-signals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(signals.DataSignals)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/watchdebugger/watchdebugger.templ`, Line: 71, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, p.Attributes)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "><!-- Event interceptor (hidden) — captures all _ds_* signal patches --><div style=\"display:none\" data-on-signal-patch-filter=\"{include: /^_ds_/}\" data-on-signal-patch=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(logExpr)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/watchdebugger/watchdebugger.templ`, Line: 78, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"></div><!-- Staleness check — mark disconnected if no event in 10s --><div style=\"display:none\" data-on-interval__duration.3s=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf(
			"%s = %s > 0 && (Date.now() - %s) < 10000",
			signals.Signal("connected"), signals.Signal("lastTs"), signals.Signal("lastTs"),
		))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/watchdebugger/watchdebugger.templ`, Line: 86, Col: 4}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"></div><!-- Collapsed: toggle button with connection dot --><button class=\"btn btn-sm btn-neutral gap-1\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.OnClick(signals.Toggle("open")))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.Show("!"+signals.Signal("open")))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "><span class=\"inline-block w-2 h-2 rounded-full\" data-class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(ds.NewDataClass().
			Add("bg-success", signals.Signal("connected")).
			Add("bg-error", "!"+signals.Signal("connected")).
			Build())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/watchdebugger/watchdebugger.templ`, Line: 99, Col: 12}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\"></span> Watch</button><!-- Expanded: inspector panel --><div class=\"card bg-base-200 shadow-xl w-96\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.Show(signals.Signal("open")))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "><div class=\"card-body p-3 gap-2\"><!-- Header --><div class=\"flex items-center justify-between\"><span class=\"font-semibold text-sm\">Watch Inspector</span> <button class=\"btn btn-ghost btn-xs\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.OnClick(signals.Set("open", "false")))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, ">✕</button></div><!-- Connection status --><div class=\"flex items-center gap-2 text-xs\"><span class=\"inline-block w-2 h-2 rounded-full\" data-class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(ds.NewDataClass().
			Add("bg-success", signals.Signal("connected")).
			Add("bg-error", "!"+signals.Signal("connected")).
			Build())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/watchdebugger/watchdebugger.templ`, Line: 126, Col: 14}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\"></span> <span")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.Text(signals.Signal("connected")+" ? 'Connected' : 'Disconnected'"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "></span> <span class=\"text-base-content/50\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.Show(signals.Signal("lastTs")+" > 0"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.Text("'Last: ' + new Date("+signals.Signal("lastTs")+").toLocaleTimeString()"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "></span></div><div class=\"divider my-0\"></div><!-- Active watches --><div class=\"text-xs\"><div class=\"font-semibold mb-1\">Active Watches</div><div class=\"flex flex-wrap gap-1\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.Text("($_dsDbgWatches || []).join(', ') || 'None'"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "></div></div><div class=\"divider my-0\"></div><!-- Live signal state --><div class=\"text-xs\"><div class=\"font-semibold mb-1\">Watch Signals</div><pre class=\"bg-base-300 p-2 rounded text-xs max-h-32 overflow-auto\" data-json-signals=\"{include: /^_ds_/}\"></pre></div><div class=\"divider my-0\"></div><!-- Event log --><div class=\"text-xs\"><div class=\"flex items-center justify-between mb-1\"><span class=\"font-semibold\">Event Log</span> <button class=\"btn btn-ghost btn-xs\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, ds.OnClick(fmt.Sprintf(
			"window.__dsDbgLog=[];var _el=document.getElementById('%s-log');if(_el)_el.textContent='Waiting for events...'",
			p.ID,
		)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, ">Clear</button></div><pre id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(p.ID + "-log")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/watchdebugger/watchdebugger.templ`, Line: 169, Col: 24}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\" class=\"bg-base-300 p-2 rounded text-xs max-h-40 overflow-y-auto whitespace-pre-wrap\">Waiting for events...</pre></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
